### ISSUE TITLE
Enduse breakdown graph (Donut chart)

### ISSUE THREAD

**Issue by manateejh** [weilix88/buildsimhub_python_api#101]
(Hi Weili! :)

In the Donut chart, I think the titles of end uses e.g. interior equipment, heating, should be the same in its size. 

Now the size is changing by making it fit into the area. So as a result, heating/cooling/fans are bigger in size than others like interior equipment. And it possibly makes the user misinterpret that those are the main contributors of energy consumption or somehow more stressed out among others.

**Comment by weilixu** [comment]
resolved. Will be soon available
