### ISSUE TITLE
Dashboard observation summary

### ISSUE THREAD

**Issue by manateejh** [weilix88/buildsimhub_python_api#103]
[BSH Dashboard Error Log by Jeannie_v2.docx](https://github.com/weilix88/buildsimhub_python_api/files/2601429/BSH.Dashboard.Error.Log.by.Jeannie_v2.docx)

Hi all, Wanted to share the observation summary I made on BSH dashboard here too.

**Comment by weilixu** [comment]
Thank you for the suggestions. All have been addressed
