### ISSUE TITLE
Uploading errors

### ISSUE THREAD

**Issue by manateejh** [weilix88/buildsimhub_python_api#106]
When using api to upload,
![image](https://user-images.githubusercontent.com/43181529/49765941-7d77d000-fc99-11e8-8859-a8e9fea25891.png)

When using bsh website to upload,
![image](https://user-images.githubusercontent.com/43181529/49766011-a5ffca00-fc99-11e8-9d7a-e9ed216c7d1c.png)

I have these two issues when uploading idf files. Let me know what happened. :(

**Comment by weilix88** [comment]
The issue was due to the hard drive space overflow on the web server and it is resolved - close the thread on Dec 17
