### ISSUE TITLE
Support csv schedules

### ISSUE THREAD

**Issue by mostaphaRoudsari** [weilix88/buildsimhub_python_api#36]
There are several cases that csv files are used for schedules. We use them to set lighting schedule, airflow, material transmittance, etc. Any plans to support sending additional csv files along with idf and epw file?

**Comment by mostaphaRoudsari** [comment]
@weilix88, most likely there will be some shared schedules and some unique schedules for each zone. For instance occupancy will be the same for all the zones with the same program but the csv files for lighting schedules which is generated from annual daylight simulation will be unique for every single zone.

I think it will be good to add an argument for additional_files which one can use to pass a list of files or a zipped file which you can unzip later in the same folder.

cc: @chriswmackey

**Comment by weilix88** [comment]
@mostaphaRoudsari @chriswmackey the API library is updated with the requested .csv schedule upload function.
A sample script can be found https://github.com/weilix88/buildsimhub_python_api/blob/master/test/upload_model_csv.py
Please try it out and let me know if that is working for you.
