### ISSUE TITLE
create_model method should be able to initiate a model under a project

### ISSUE THREAD

**Issue by weilixu** [weilix88/buildsimhub_python_api#6]
We are adding this feature that allows create_model to create an energy model branch.
If you want to upload your models to a completely new energy model branch, you can just ignore the model_key input, and the API should be able to detect it and create a new energy model branch to host your uploaded model.

Example:
new_simulation_job.create_model() ->
return: new energy model branch API key, and success (given your model is valide)

**Comment by weilix88** [comment]
This is completed
